export PATH=$PATH:$HOME/.kube/plugins
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="spaceship"
plugins=(
  git
  kubectl
  aws
  battery
  pip
)
source $ZSH/oh-my-zsh.sh
source $ZSH/zsh-autosuggestions.zsh
source $HOME/.kube/.kubens
source $HOME/.kube/.kubectx
source <(kubectl completion zsh)
complete -F __start_kubectl k
# complete -C '/opt/homebrew/bin/aws_completer' aws
alias ll="ls -alh"
alias ns="kubens"
alias ctx="kubectx"
alias p=kgp
alias pw=kgpwide
alias s=kgs
alias ss=kgss
alias ssw=kgsswide
alias d=kgd
alias dw=kgdwide
alias kak="kubectl apply -k"
alias kghpa="kubectl get hpa"
alias kdelhpa="kubectl delete hpa"
export HOMEBREW_NO_AUTO_UPDATE=1
fpath=($fpath /opt/homebrew/share/zsh/site-functions)
autoload -U compinit
compinit
alias netstat-l="sudo lsof -i -P | grep LISTEN"
